---
name: cmpsc-100-fall-2018-practical5
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalfive/RollAndSumDice.java:
            --single 6 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4
            --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 13
# --> check that the program executes and produces 4 lines of output
# --> check that the output contains different fragments
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
--command "gradle -q --console plain run" --fragment "Sum" --count 1 --exact
--command "gradle -q --console plain run" --fragment "Face Value" --count 3 --exact
